/** Structurally compatible with `EntityEntry` (see `entities.ts`). */
export interface TechMonitoringCompanyEntry {
  id: string;
  type: 'company';
  name: string;
  aliases: string[];
  keywords: string[];
  sector?: string;
  related?: string[];
}

/**
 * Curated tech / science watchlist merged into ENTITY_REGISTRY.
 * Extend this list as needed; keep `id` stable (used for linking).
 */
export const TECH_MONITORING_COMPANIES: TechMonitoringCompanyEntry[] = [
  {
    id: 'OPENAI',
    type: 'company',
    name: 'OpenAI',
    aliases: ['openai', 'chatgpt', 'gpt-4', 'gpt-5', 'sam altman'],
    keywords: ['llm', 'generative ai', 'api', 'model release', 'safety', 'compute'],
    sector: 'Technology',
    related: ['MSFT', 'GOOGL', 'NVDA'],
  },
  {
    id: 'ANTHROPIC',
    type: 'company',
    name: 'Anthropic',
    aliases: ['anthropic', 'claude', 'constitutional ai'],
    keywords: ['llm', 'enterprise ai', 'safety', 'funding'],
    sector: 'Technology',
    related: ['GOOGL', 'AMZN'],
  },
  {
    id: 'MISTRAL',
    type: 'company',
    name: 'Mistral AI',
    aliases: ['mistral', 'mistral ai'],
    keywords: ['open weights', 'europe', 'llm', 'inference'],
    sector: 'Technology',
    related: ['NVDA', 'MSFT'],
  },
  {
    id: 'META',
    type: 'company',
    name: 'Meta Platforms',
    aliases: ['meta', 'facebook', 'instagram', 'whatsapp', 'llama'],
    keywords: ['social', 'metaverse', 'open source llm', 'ads', 'reality labs'],
    sector: 'Technology',
    related: ['GOOGL', 'AAPL'],
  },
  {
    id: 'TSLA',
    type: 'company',
    name: 'Tesla Inc.',
    aliases: ['tesla', 'tsla', 'elon musk', 'cybertruck'],
    keywords: ['ev', 'battery', 'fsd', 'energy', 'megapack'],
    sector: 'Consumer Cyclical',
    related: ['NVDA', 'QCOM'],
  },
  {
    id: 'AMD',
    type: 'company',
    name: 'Advanced Micro Devices',
    aliases: ['amd', 'ryzen', 'epyc', 'radeon', 'lisa su'],
    keywords: ['cpu', 'gpu', 'datacenter', 'ai accelerator', 'Xilinx'],
    sector: 'Technology',
    related: ['NVDA', 'INTC', 'TSM'],
  },
  {
    id: 'INTC',
    type: 'company',
    name: 'Intel Corporation',
    aliases: ['intel', 'intc', 'pat gelsinger'],
    keywords: ['foundry', 'cpu', 'process node', 'ai pc', 'idm 2.0'],
    sector: 'Technology',
    related: ['AMD', 'TSM', 'NVDA'],
  },
  {
    id: 'AVGO',
    type: 'company',
    name: 'Broadcom Inc.',
    aliases: ['broadcom', 'avgo', 'vmware'],
    keywords: ['semiconductor', 'networking', 'software', 'ai asic'],
    sector: 'Technology',
    related: ['NVDA', 'QCOM'],
  },
  {
    id: 'QCOM',
    type: 'company',
    name: 'Qualcomm Inc.',
    aliases: ['qualcomm', 'qcom', 'snapdragon'],
    keywords: ['mobile soc', '5g', 'on-device ai', 'automotive'],
    sector: 'Technology',
    related: ['AAPL', 'AVGO'],
  },
  {
    id: 'CRM',
    type: 'company',
    name: 'Salesforce',
    aliases: ['salesforce', 'crm', 'einstein', 'slack'],
    keywords: ['saas', 'crm', 'enterprise ai', 'data cloud'],
    sector: 'Technology',
    related: ['MSFT', 'ORCL'],
  },
  {
    id: 'ORCL',
    type: 'company',
    name: 'Oracle Corporation',
    aliases: ['oracle', 'orcl', 'larry ellison'],
    keywords: ['database', 'cloud', 'oci', 'enterprise'],
    sector: 'Technology',
    related: ['MSFT', 'AMZN'],
  },
  {
    id: 'NOW',
    type: 'company',
    name: 'ServiceNow',
    aliases: ['servicenow', 'now platform'],
    keywords: ['workflow', 'itsm', 'enterprise automation'],
    sector: 'Technology',
    related: ['CRM', 'MSFT'],
  },
  {
    id: 'SNOW',
    type: 'company',
    name: 'Snowflake Inc.',
    aliases: ['snowflake', 'snow'],
    keywords: ['data cloud', 'warehouse', 'analytics', 'iceberg'],
    sector: 'Technology',
    related: ['MSFT', 'GOOGL'],
  },
  {
    id: 'DDOG',
    type: 'company',
    name: 'Datadog Inc.',
    aliases: ['datadog', 'ddog'],
    keywords: ['observability', 'apm', 'security', 'logs'],
    sector: 'Technology',
    related: ['MSFT', 'NOW'],
  },
  {
    id: 'NET',
    type: 'company',
    name: 'Cloudflare',
    aliases: ['cloudflare', 'net'],
    keywords: ['cdn', 'zero trust', 'workers', 'ddos'],
    sector: 'Technology',
    related: ['DDOG', 'ZS'],
  },
  {
    id: 'ZS',
    type: 'company',
    name: 'Zscaler',
    aliases: ['zscaler', 'zs'],
    keywords: ['zero trust', 'sse', 'security'],
    sector: 'Technology',
    related: ['NET', 'PANW'],
  },
  {
    id: 'PANW',
    type: 'company',
    name: 'Palo Alto Networks',
    aliases: ['palo alto', 'panw', 'prisma'],
    keywords: ['firewall', 'soc', 'cloud security', 'sase'],
    sector: 'Technology',
    related: ['CRWD', 'ZS'],
  },
  {
    id: 'CRWD',
    type: 'company',
    name: 'CrowdStrike',
    aliases: ['crowdstrike', 'crwd', 'falcon'],
    keywords: ['endpoint', 'edr', 'threat intel', 'identity'],
    sector: 'Technology',
    related: ['PANW', 'MSFT'],
  },
  {
    id: 'PLTR',
    type: 'company',
    name: 'Palantir Technologies',
    aliases: ['palantir', 'pltr', 'gotham', 'foundry', 'aip'],
    keywords: ['government', 'ontology', 'decision intelligence'],
    sector: 'Technology',
    related: ['MSFT', 'NOW'],
  },
  {
    id: 'SHOP',
    type: 'company',
    name: 'Shopify',
    aliases: ['shopify', 'shop'],
    keywords: ['ecommerce', 'payments', 'merchant'],
    sector: 'Technology',
    related: ['AMZN', 'SQ'],
  },
  {
    id: 'UBER',
    type: 'company',
    name: 'Uber Technologies',
    aliases: ['uber'],
    keywords: ['mobility', 'delivery', 'maps', 'autonomous'],
    sector: 'Technology',
    related: ['LYFT', 'GOOGL'],
  },
  {
    id: 'ABNB',
    type: 'company',
    name: 'Airbnb',
    aliases: ['airbnb', 'abnb'],
    keywords: ['travel', 'marketplace', 'hosting'],
    sector: 'Consumer Cyclical',
    related: ['BKNG', 'EXPE'],
  },
  {
    id: 'COIN',
    type: 'company',
    name: 'Coinbase',
    aliases: ['coinbase', 'coin'],
    keywords: ['crypto exchange', 'custody', 'base chain'],
    sector: 'Financial Services',
    related: ['MSTR', 'HOOD'],
  },
  {
    id: 'HOOD',
    type: 'company',
    name: 'Robinhood',
    aliases: ['robinhood', 'hood'],
    keywords: ['retail trading', 'options', 'crypto'],
    sector: 'Financial Services',
    related: ['COIN', 'IBKR'],
  },
  {
    id: 'ASML',
    type: 'company',
    name: 'ASML Holding',
    aliases: ['asml', 'euv lithography'],
    keywords: ['lithography', 'semiconductor equipment', 'euv'],
    sector: 'Technology',
    related: ['TSM', 'NVDA'],
  },
  {
    id: 'TSM',
    type: 'company',
    name: 'Taiwan Semiconductor',
    aliases: ['tsmc', 'taiwan semi', 'tsm'],
    keywords: ['foundry', '3nm', 'advanced packaging', 'coWoS'],
    sector: 'Technology',
    related: ['ASML', 'NVDA', 'AAPL'],
  },
  {
    id: '005930.KS',
    type: 'company',
    name: 'Samsung Electronics',
    aliases: ['samsung', 'galaxy', 'exynos'],
    keywords: ['memory', 'display', 'foundry', 'mobile'],
    sector: 'Technology',
    related: ['AAPL', 'TSM'],
  },
  {
    id: 'SONY',
    type: 'company',
    name: 'Sony Group',
    aliases: ['sony', 'playstation', 'ps5'],
    keywords: ['imaging', 'sensors', 'gaming', 'entertainment'],
    sector: 'Technology',
    related: ['MSFT', 'NTDOY'],
  },
  {
    id: 'SAP',
    type: 'company',
    name: 'SAP SE',
    aliases: ['sap', 's/4hana', 'business one'],
    keywords: ['erp', 'supply chain', 'analytics'],
    sector: 'Technology',
    related: ['ORCL', 'NOW'],
  },
  {
    id: 'ADBE',
    type: 'company',
    name: 'Adobe Inc.',
    aliases: ['adobe', 'adbe', 'photoshop', 'creative cloud'],
    keywords: ['creative software', 'document cloud', 'firefly'],
    sector: 'Technology',
    related: ['MSFT', 'CRM'],
  },
  {
    id: 'INTU',
    type: 'company',
    name: 'Intuit',
    aliases: ['intuit', 'turbotax', 'quickbooks', 'mailchimp'],
    keywords: ['fintech', 'smb', 'tax', 'accounting'],
    sector: 'Technology',
    related: ['SQ', 'PYPL'],
  },
  {
    id: 'SQ',
    type: 'company',
    name: 'Block Inc.',
    aliases: ['block', 'square', 'cash app'],
    keywords: ['payments', 'seller', 'bitcoin'],
    sector: 'Technology',
    related: ['PYPL', 'INTU'],
  },
  {
    id: 'PYPL',
    type: 'company',
    name: 'PayPal',
    aliases: ['paypal', 'pypl', 'venmo'],
    keywords: ['payments', 'wallet', 'checkout'],
    sector: 'Financial Services',
    related: ['SQ', 'SHOP'],
  },
];
